import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { getSortedPostsData } from '../../utils/posts';

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();

  return {
    props: {
      allPostsData
    },
  };
}

const inter = Inter({ subsets: ['latin'] })

export default function Home({ allPostsData }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <section>
          <h2 >Blog</h2>

          <ul>
            {allPostsData.map(({ id, date, title, description }) => (
              <li key={id}>
                {title}
                <br />
                {id}
                <br />
                {date}
                <br />
                {description}
              </li>
            ))}
          </ul>
        </section>

      </main>
    </>
  )
}
